services:
  backend: 
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - db_data:/app/db
    environment:
      - DATABASE_URL=sqlite:db/data.db?mode=rwc
      - HOST=0.0.0.0
      - PORT=8080
      - ML_SERVICE_URL=http://ml_service:8000
      # Вот так делать не стоит
      - JWT_SECRET=change-me-in-production
      # И вот так не надо
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminpass123
      # Но пусть пока так будет

  ml_service:
    build: ./ml_service
    depends_on:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/db
      - ml_artifacts:/app/artifacts
    
  nginx:
    build: ./frontend
    ports:
      - "8888:80"
    depends_on:
      - backend

volumes:
  db_data:
  ml_artifacts: